spring:
  application:
    name: car-cheap
  datasource:
    url: jdbc:h2:mem:carcheapdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
  h2:
    console:
      enabled: true

server:
  port: 8090
