spring:
  application:
    name: car-cheap
  datasource:
    url: jdbc:h2:mem:carcheapdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
  h2:
    console:
      enabled: true
  jpa:
    defer-datasource-initialization: true
  sql:
    init:
      mode: always

server:
  port: 8090

logging:
  level:
    root: INFO
    org.hibernate: ERROR
  pattern:
    console: "%d{dd-MM-yyyy HH:mm:ss} [%-5level] %c{1}: %msg%n"
